# ESTRUTURAS DE CONDIÇÃO

'''
A ESTRUTURA DE CONDIÇÃO SERVE PARA CRIAR UMA BIFURCAÇÃO NO NOSSO CÓDIGO;
OU SEJA, EXECUTAR UM DETERMINADO TRECHO APENAS SE UMA CONDIÇÃO 
FOR VERDADEIRA, POR EXEMPLO:
A MAIS FAMOSA É A ESTRUTURA IF, PODEM TAMBÉM ELSE E ELIF.

'''

