# ALGORITMOS

'''
O ALGORITMO É UM PASSO A PASSO PARA RESOLVER UMA DETERMINADA 
TAREFA;
OU SEJA, UM SOFTWARE OU UM PROGRAMA TEM UMA SERIE DE ALGORITMOS;
EXEMPLO DE ALGORITMP PARA TROCAR A LÂMPADA;

COMPRAR LÂMPADA NOVA, COLOCAR A ESCADA PRÓXIMA A LÂMPADA,
RETIRAR LÂMPADA ANTIGA, INSERIR LÂMPADA NOVA,
DESCARTAR LÂMPADA ANTIGA.

'''