# EXERCICIO 19

# TROCAR PNEU

'''
1 - RETIRAR O MACACO DO CARRO
2 - AFROUXAR OS PARAFUSOS DO PNEU
3 - IÇAR O CARRO COM O MACACO
4 - TERMINAR DE DESPARAFUSAR
5 - RETIRAR O PNEU FURADO
6 - COLOCAR O ESTEPE NO LUGAR
7 - PARAFUSAR O PNEU
8 - ABAIXAR O CARRO
9 - RETIRAR O MACACO DO CARRO
10 - GUARDAR MACACO
11 - GUARDAR O PNEU FURADO
'''
