# LÓGICA DE PROGRAMAÇÃO 

'''
UMA ELABORAÇÃO DE SEQUENCIAS PARA ATINGIR DETERMINADO OBJETIVO;
OU SEJA, AS LINHAS DE CODIGO SENDO EXECUTADAS DO NOSSO PROGRAMA ALTERNANDO OS DADOS

PORÉM SÃO ADICIONADOS OUTROS RECURSOS COMO: ESTRUTURAS DE CONDIÇÃO E 
ESTRUTURAS DE REPETIÇÃO.

'''
